In [1]:
import pre_process as p_p

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from math import sqrt

In [2]:
df = pd.read_csv("fake_reg_hidden_data.csv")
df = df.sample(frac = 1)
df.reset_index(inplace=True)
        
try:
    df=df.drop(['index'],axis=1)
except:
    pass

df.head()

,Doctor Name,City,Specialization,Doctor Qualification,Experience(Years),Total_Reviews,Patient Satisfaction Rate(%age),Avg Time to Patients(mins),Wait Time(mins),Hospital Address,Doctors Link,Fee(PKR)
0,Dr. Ayesha Tahir,VEHARI,General Physician,MBBS,3.0,2,100,14,11,No Address Available,https://www.marham.pk/online-consultation/gene...,500
1,Asst. Prof. Dr. Tahir Khan,QUETTA,"Pulmonologist / Lung Specialist, General Physi...","MBBS, FCPS",10.0,185,98,14,11,"Yaseen Hospital, Quetta City, Quetta",https://www.marham.pk/doctors/quetta/pulmonolo...,1000
2,Dr. Saadat Hashmi,ISLAMABAD,Urologist,"MBBS, FCPS",15.0,22,96,15,9,"Maryam Memorial Hospital, Afzal Town, Rawalpindi",https://www.marham.pk/doctors/islamabad/urolog...,2500
3,Dr. M.irfan,GUJRANWALA,Urologist,"MBBS,FCPS",10.0,0,94,14,11,"Gondal Medical Complex Hospital, Civil Lines, ...",No Link Available,1000
4,Dr. Javed Hussain,HYDERABAD,Pediatrician,"MBBS , Diploma in Child Health (DCH)",10.0,2,100,20,0,"Mehran Hospital, Qasimabad, Hyderabad",https://www.marham.pk/doctors/hyderabad/pediat...,700

In [3]:
df.isna().sum()

Doctor Name                        0
City                               1
Specialization                     0
Doctor Qualification               1
Experience(Years)                  1
Total_Reviews                      0
Patient Satisfaction Rate(%age)    0
Avg Time to Patients(mins)         0
Wait Time(mins)                    0
Hospital Address                   1
Doctors Link                       0
Fee(PKR)                           0
dtype: int64

In [4]:
df = p_p.pre_process(df, 'Fee(PKR)')

c:\Users\mahmo\Desktop\Code\Machine Learning\Machine Learning Project\MS2\pre_process.py:147: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Hospital Name'].iloc[index] = 0
c:\Users\mahmo\Desktop\Code\Machine Learning\Machine Learning Project\MS2\pre_process.py:147: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Hospital Name'].iloc[index] = 0
c:\Users\mahmo\Desktop\Code\Machine Learning\Machine Learning Project\MS2\pre_process.py:147: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Hospital Name'].iloc[index] = 0
c:\Users\mahmo\Desktop\Code\Machine Learning\Machine Learning Project\MS2\pre_process.py:147: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Hospital Name'].iloc[index] = 0
c:\Users\mahmo\Desktop\Code\Machine Learning\Machine Learning Project\MS2\pre_process.py:147: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Hospital Name'].iloc[index] = 0
c:\Users\mahmo\Desktop\Code\Machine Learning\Machine Learning Project\MS2\pre_process.py:147: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Hospital Name'].iloc[index] = 0
c:\Users\mahmo\Desktop\Code\Machine Learning\Machine Learning Project\MS2\pre_process.py:147: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Hospital Name'].iloc[index] = 0

In [5]:
df.head()

,MBBS,FCPS,MCPS,MS,MD,FRCS,City,Specialization,EXP(YRs),Hospital Name,#Reviews,Doctors Link,Fee(PKR)
0,1,0,0,0,0,0,1065.720626,619.676375,3.0,0.000000,2,1,500
1,1,1,0,0,0,0,1350.965636,1186.465265,10.0,1187.492486,185,1,1000
2,1,1,0,0,0,0,1836.103405,1431.312425,15.0,1384.179498,22,1,2500
3,1,1,0,0,0,0,1298.551883,1431.312425,10.0,1174.000421,0,0,1000
4,1,0,0,0,0,0,1000.593622,914.326925,10.0,1149.984244,2,1,700

In [6]:

import pickle as pkl
RS = pkl.load(open("scaler_reg.pkl", "rb"))

In [7]:
X_ = df.drop('Fee(PKR)', axis=1).values
X_ = RS.transform(X_)
y_ = df['Fee(PKR)'].values

In [8]:
model = pkl.load(open("ET_reg.pkl", "rb"))

preds = model.predict(X_)

mse = mean_squared_error(y_, preds)
r2 = r2_score(y_, preds)

print(sqrt(mse))
print(r2)

402.3340394497227
0.7353084792302766